<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseSystemSourceProjects Condition="'$(UseSystemSourceProjects)' == ''">true</UseSystemSourceProjects>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concertable.Payment.TestKit" />
    <PackageReference Include="Concertable.Customer.TestKit" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="Concertable.Auth.Hosting" />
    <PackageReference Include="Concertable.Customer.Hosting" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Concertable.Shared\tests\Concertable.Testing.E2E\Concertable.Testing.E2E.csproj" />
    <ProjectReference Include="..\..\..\..\tests\Concertable.System.E2E\Concertable.System.E2E.csproj" />
    <ProjectReference Include="..\..\..\..\Concertable.Payment\tests\E2ETests\Concertable.Payment.E2ETests.Helpers\Concertable.Payment.E2ETests.Helpers.csproj" />
    <ProjectReference Include="..\..\..\..\Concertable.Search\tests\E2ETests\Concertable.Search.E2ETests.Helpers\Concertable.Search.E2ETests.Helpers.csproj" />
    <ProjectReference Include="..\..\..\..\tests\Concertable.System.E2E.Source\Concertable.System.E2E.Source.csproj"
                      Condition="'$(UseSystemSourceProjects)' == 'true'" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.E2E.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Concertable.Testing" />
    <Using Include="Concertable.Testing.E2E" />
    <Using Include="Concertable.Payment.E2ETests.Helpers" />
  </ItemGroup>

</Project>
