using Concertable.B2B.Hosting.Frontend;
using Concertable.Customer.Hosting.Frontend;
using Concertable.AppHost;
using Concertable.Auth.Hosting;
using Concertable.B2B.Hosting;
using Concertable.Customer.Hosting;
using Concertable.Payment.Hosting;
using Concertable.Search.Hosting;

var builder = StrictDistributedApplication.CreateBuilder(args);
var sql = builder.AddSqlServerContainer();
var b2bDb = sql.AddDatabase(B2BConstants.Database);
var authDb = sql.AddDatabase(AuthConstants.Database);
var customerDb = sql.AddDatabase(CustomerConstants.Database);
var searchDb = sql.AddDatabase(SearchConstants.Database);
var paymentDb = sql.AddDatabase(PaymentConstants.Database);
var (storage, blobs) = builder.AddAzureStorage();
var asb = builder.AddServiceBus();
asb.Topology().AddB2BTopology().AddCustomerTopology().AddSearchTopology().AddPaymentTopology().AddAuthTopology().RunAsEmulator();
var auth = builder.AddAuth<Projects.Concertable_Auth>(authDb, asb);
auth.WithSpaClients(SystemLocalSpaSurfaces.AuthClients);
var paymentWeb = builder.AddPaymentWeb<Projects.Concertable_Payment_Web>(auth, paymentDb, asb);
var api = builder.AddB2BWeb<Projects.Concertable_B2B_Web>(b2bDb, auth, storage, blobs, asb, paymentWeb);
auth.WithEnvironment("Services__B2BApiUrl", api.GetEndpoint("https"));
auth.WithEnvironment("ServiceAuth__AuthClientId", "concertable-auth");
builder.AddB2BWorkers<Projects.Concertable_B2B_Workers>(b2bDb, paymentWeb, auth);
var customerWeb = builder.AddCustomerWeb<Projects.Concertable_Customer_Web>(auth, customerDb, asb, paymentWeb);
auth.WithEnvironment("Services__CustomerApiUrl", customerWeb.GetEndpoint("https"));
var searchWeb = builder.AddSearchWeb<Projects.Concertable_Search_Web>(auth, searchDb);
builder.AddSearchWorkers<Projects.Concertable_Search_Workers>(searchDb, asb);
builder.AddPaymentWorkers<Projects.Concertable_Payment_Workers>(paymentDb, asb);
builder.AddCustomerSpa(api, customerWeb, auth);
builder.AddVenueSpa(api, auth);
builder.AddArtistSpa(api, auth);
builder.AddBusinessSpa(api, auth);
builder.AddAdminSpa(api, auth);
if (builder.AddMobile(api, auth, searchWeb, customerWeb, paymentWeb) is { } mobileTunnel)
    auth.WithMobilePublicUrl(mobileTunnel.GetEndpoint(auth, "https"));
builder.AddStripeCli(paymentWeb);
builder.Build().Run();
