<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.3.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Concertable.AppHost</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>c52698d3-c78a-4f7c-a514-e5ce072740f9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concertable.AppHost.Shared" />
    <PackageReference Include="Concertable.Auth.Hosting" />
    <PackageReference Include="Concertable.B2B.Hosting" />
    <PackageReference Include="Concertable.Customer.Hosting" />
    <PackageReference Include="Concertable.Payment.Hosting" />
    <PackageReference Include="Concertable.Search.Hosting" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\compatibility\local.yaml" Link="compatibility\local.yaml" />
  </ItemGroup>

</Project>
